<?php
	class PharauroaMessageType {
		const C2S_ACTION = 0;
		const C2S_CHOOSECHARACTER = 1;
		const C2S_LOGIN_REQUESTKEY = 2;
		const C2S_LOGIN_SENDNONCENAMEANDPASSWORD = 3;
		const C2S_LOGIN_SENDPROMISE = 4;
		const C2S_LOGOUT = 5;
		const C2S_OUTOFSYNC = 6;
		const C2S_TRANSFER_ACK = 7;
		const C2S_KEEPALIVE = 8;
		const S2C_CHARACTERLIST = 9;
		const S2C_CHOOSECHARACTER_ACK = 10;
		const S2C_CHOOSECHARACTER_NACK = 11;
		const S2C_INVALIDMESSAGE = 12;
		const S2C_LOGIN_ACK = 13;
		const S2C_LOGIN_NACK = 14;
		const S2C_LOGIN_SENDKEY = 15;
		const S2C_LOGIN_SENDNONCE = 16;
		const S2C_LOGOUT_ACK = 17;
		const S2C_LOGOUT_NACK = 18;
		const S2C_PERCEPTION = 19;
		const S2C_SERVERINFO = 20;
		const S2C_TRANSFER = 21;
		const S2C_TRANSFER_REQ = 22;
		const C2S_CREATEACCOUNT = 23;
		const S2C_CREATEACCOUNT_ACK = 24;
		const S2C_CREATEACCOUNT_NACK = 25;
		const C2S_CREATECHARACTER = 26;
		const S2C_CREATECHARACTER_ACK = 27;
		const S2C_CREATECHARACTER_NACK = 28;
		const S2C_CONNECT_NACK = 29;
		const C2S_LOGIN_SENDNONCENAMEPASSWORDANDSEED = 30;
		const S2C_LOGIN_MESSAGE_NACK = 31;
		const P2S_CREATECHARACTER = 32;
		const P2S_CREATEACCOUNT = 33;
	}
